build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
      dependencies:
        before:
          - sudo apt-get install -y libyaml libyaml-dev
          - pecl install redis
          - pecl install yaml

filter:
  paths:
    - 'src/*'
tools:
  php_code_sniffer:
    config:
      standard: PSR12
    filter:
      paths: ['src']
  php_sim: true
  php_mess_detector: true
  php_pdepend: true
  php_analyzer: true
  php_cpd: true
