# For local development only.

version: '3'

services:
  cphalcon-8.0:
    container_name: phalcon-8.0
    hostname: phalcon-80
    build: docker/8.0
    working_dir: /srv
    volumes:
      - .:/srv

  cphalcon-8.1:
    container_name: phalcon-8.1
    hostname: phalcon-81
    build: docker/8.1
    working_dir: /srv
    volumes:
      - .:/srv

  mysql:
    container_name: phalcon-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=phalcon
      - MYSQL_DATABASE=phalcon
      - MYSQL_PASSWORD=secret

  postgres:
    container_name: phalcon-postgres
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=phalcon
      - POSTGRES_DB=phalcon

  redis:
    container_name: phalcon-redis
    image: redis:5-alpine

  memcached:
    container_name: phalcon-memcached
    image: memcached:1.5-alpine
