# For local development only.
services:
  phalcon-8.1:
    container_name: phalcon-8.1
    hostname: phalcon-81
    build: resources/docker/8.1
    working_dir: /srv
    volumes:
      - .:/srv
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phalcon-8.2:
    container_name: phalcon-8.2
    hostname: phalcon-82
    build: resources/docker/8.2
    working_dir: /srv
    volumes:
      - .:/srv
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phalcon-8.3:
    container_name: phalcon-8.3
    hostname: phalcon-83
    build: resources/docker/8.3
    working_dir: /srv
    volumes:
      - .:/srv
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    container_name: phalcon-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DATA_MYSQL_PASS}
      - MYSQL_USER=${DATA_MYSQL_USER}
      - MYSQL_DATABASE=${DATA_MYSQL_NAME}
      - MYSQL_PASSWORD=${DATA_MYSQL_PASS}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    container_name: phalcon-postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${DATA_POSTGRES_PASS}
      - POSTGRES_USER=${DATA_POSTGRES_USER}
      - POSTGRES_DB=${DATA_POSTGRES_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongodb:
    container_name: phalcon-mongodb
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATA_MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATA_MONGODB_PASS}
      - MONGO_INITDB_DATABASE=${DATA_MONGODB_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    container_name: phalcon-redis
    image: redis:6-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis-node-0:
    container_name: phalcon-redis-node-0
    image: docker.io/bitnami/redis-cluster:7.2
    environment:
      - REDIS_PASSWORD=${DATA_REDIS_PASS}
      - 'REDIS_NODES=phalcon-redis-node-0 phalcon-redis-node-1 phalcon-redis-node-2 phalcon-redis-node-3 phalcon-redis-node-4 phalcon-redis-node-5'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis-node-1:
    container_name: phalcon-redis-node-1
    image: docker.io/bitnami/redis-cluster:7.2
    environment:
      - REDIS_PASSWORD=${DATA_REDIS_PASS}
      - 'REDIS_NODES=phalcon-redis-node-0 phalcon-redis-node-1 phalcon-redis-node-2 phalcon-redis-node-3 phalcon-redis-node-4 phalcon-redis-node-5'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis-node-2:
    container_name: phalcon-redis-node-2
    image: docker.io/bitnami/redis-cluster:7.2
    environment:
      - REDIS_PASSWORD=${DATA_REDIS_PASS}
      - 'REDIS_NODES=phalcon-redis-node-0 phalcon-redis-node-1 phalcon-redis-node-2 phalcon-redis-node-3 phalcon-redis-node-4 phalcon-redis-node-5'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis-node-3:
    container_name: phalcon-redis-node-3
    image: docker.io/bitnami/redis-cluster:7.2
    environment:
      - REDIS_PASSWORD=${DATA_REDIS_PASS}
      - 'REDIS_NODES=phalcon-redis-node-0 phalcon-redis-node-1 phalcon-redis-node-2 phalcon-redis-node-3 phalcon-redis-node-4 phalcon-redis-node-5'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis-node-4:
    container_name: phalcon-redis-node-4
    image: docker.io/bitnami/redis-cluster:7.2
    environment:
      - REDIS_PASSWORD=${DATA_REDIS_PASS}
      - 'REDIS_NODES=phalcon-redis-node-0 phalcon-redis-node-1 phalcon-redis-node-2 phalcon-redis-node-3 phalcon-redis-node-4 phalcon-redis-node-5'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis-node-5:
    container_name: phalcon-redis-node-5
    image: docker.io/bitnami/redis-cluster:7.2
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - REDIS_PASSWORD=${DATA_REDIS_PASS}
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=phalcon-redis-node-0 phalcon-redis-node-1 phalcon-redis-node-2 phalcon-redis-node-3 phalcon-redis-node-4 phalcon-redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  memcached:
    container_name: phalcon-memcached
    image: memcached:1.6-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
