<?php

/**
 * This file is part of the Phalcon Framework.
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Phalcon\Tests\Database\DataMapper\Info\Adapter\Pgsql;

use Phalcon\DataMapper\Info\Adapter\Pgsql;
use Phalcon\DataMapper\Pdo\Exception\Exception;
use Phalcon\Tests\AbstractDatabaseTestCase;

final class ListColumnsTest extends AbstractDatabaseTestCase
{
    /**
     * @since  2025-01-14
     *
     * @group pgsql
     *
     * @return void
     * @throws Exception
     */
    public function testDmInfoAdapterPgsqlListTables(): void
    {
        $connection = self::getDataMapperConnection();

        $pgsql  = new Pgsql($connection);
        $schema = $pgsql->getCurrentSchema();

        $expected = [
            'field_primary'           => [
                'name'            => 'field_primary',
                'type'            => 'integer',
                'size'            => 32,
                'scale'           => 0,
                'isNullable'      => false,
                'defaultValue'    => 0,
                'isAutoIncrement' => true,
                'isPrimary'       => true,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_blob'              => [
                'name'            => 'field_blob',
                'type'            => 'bytea',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_binary'            => [
                'name'            => 'field_binary',
                'type'            => 'bytea',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_bit'               => [
                'name'            => 'field_bit',
                'type'            => 'bit',
                'size'            => 10,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_bit_default'       => [
                'name'            => 'field_bit_default',
                'type'            => 'bit',
                'size'            => 10,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => '1',
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_bigint'            => [
                'name'            => 'field_bigint',
                'type'            => 'bigint',
                'size'            => 64,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_bigint_default'    => [
                'name'            => 'field_bigint_default',
                'type'            => 'bigint',
                'size'            => 64,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => 1,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_boolean'           => [
                'name'            => 'field_boolean',
                'type'            => 'boolean',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_boolean_default'   => [
                'name'            => 'field_boolean_default',
                'type'            => 'boolean',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_char'              => [
                'name'            => 'field_char',
                'type'            => 'character',
                'size'            => 10,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_char_default'      => [
                'name'            => 'field_char_default',
                'type'            => 'character',
                'size'            => 10,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => 'ABC',
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_decimal'           => [
                'name'            => 'field_decimal',
                'type'            => 'numeric',
                'size'            => 10,
                'scale'           => 4,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_decimal_default'   => [
                'name'            => 'field_decimal_default',
                'type'            => 'numeric',
                'size'            => 10,
                'scale'           => 4,
                'isNullable'      => true,
                'defaultValue'    => 14.5678,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_enum'              => [
                'name'            => 'field_enum',
                'type'            => 'text',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_integer'           => [
                'name'            => 'field_integer',
                'type'            => 'integer',
                'size'            => 32,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_integer_default'   => [
                'name'            => 'field_integer_default',
                'type'            => 'integer',
                'size'            => 32,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => 1,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_json'              => [
                'name'            => 'field_json',
                'type'            => 'json',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_float'             => [
                'name'            => 'field_float',
                'type'            => 'real',
                'size'            => 24,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_float_default'     => [
                'name'            => 'field_float_default',
                'type'            => 'real',
                'size'            => 24,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => 14.5678,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_date'              => [
                'name'            => 'field_date',
                'type'            => 'date',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_date_default'      => [
                'name'            => 'field_date_default',
                'type'            => 'date',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => '2018-10-01',
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_datetime'          => [
                'name'            => 'field_datetime',
                'type'            => 'timestamp without time zone',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_datetime_default'  => [
                'name'            => 'field_datetime_default',
                'type'            => 'timestamp without time zone',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => '2018-10-01 12:34:56',
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_time'              => [
                'name'            => 'field_time',
                'type'            => 'time without time zone',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_time_default'      => [
                'name'            => 'field_time_default',
                'type'            => 'time without time zone',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => '12:34:56',
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_timestamp'         => [
                'name'            => 'field_timestamp',
                'type'            => 'timestamp without time zone',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_timestamp_default' => [
                'name'            => 'field_timestamp_default',
                'type'            => 'timestamp without time zone',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => '2018-10-01 12:34:56',
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_timestamp_current' => [
                'name'            => 'field_timestamp_current',
                'type'            => 'timestamp without time zone',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_mediumint'         => [
                'name'            => 'field_mediumint',
                'type'            => 'integer',
                'size'            => 32,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_mediumint_default' => [
                'name'            => 'field_mediumint_default',
                'type'            => 'integer',
                'size'            => 32,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => 1,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_smallint'          => [
                'name'            => 'field_smallint',
                'type'            => 'smallint',
                'size'            => 16,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_smallint_default'  => [
                'name'            => 'field_smallint_default',
                'type'            => 'smallint',
                'size'            => 16,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => 1,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_tinyint'           => [
                'name'            => 'field_tinyint',
                'type'            => 'smallint',
                'size'            => 16,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_tinyint_default'   => [
                'name'            => 'field_tinyint_default',
                'type'            => 'smallint',
                'size'            => 16,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => 1,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_longtext'          => [
                'name'            => 'field_longtext',
                'type'            => 'text',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_mediumtext'        => [
                'name'            => 'field_mediumtext',
                'type'            => 'text',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_tinytext'          => [
                'name'            => 'field_tinytext',
                'type'            => 'text',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_text'              => [
                'name'            => 'field_text',
                'type'            => 'text',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_varbinary'         => [
                'name'            => 'field_varbinary',
                'type'            => 'bytea',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_varchar'           => [
                'name'            => 'field_varchar',
                'type'            => 'character varying',
                'size'            => 10,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_varchar_default'   => [
                'name'            => 'field_varchar_default',
                'type'            => 'character varying',
                'size'            => 10,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => 'D',
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
        ];

        $actual = $pgsql->listColumns($schema, 'co_dialect');

        $this->assertSame($expected, $actual);
    }
}
