<?php

/**
 * This file is part of the Phalcon Framework.
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Phalcon\Tests\Database\DataMapper\Info\Adapter\Mysql;

use Phalcon\DataMapper\Info\Adapter\Mysql;
use Phalcon\DataMapper\Pdo\Connection;
use Phalcon\Tests\AbstractDatabaseTestCase;

final class ListColumnsTest extends AbstractDatabaseTestCase
{
    /**
     * @since  2025-01-14
     *
     * @group mysql
     */
    public function testDmInfoAdapterMysqlListTables(): void
    {
        /** @var Connection $connection */
        $connection = self::getDataMapperConnection();

        $mysql  = new Mysql($connection);
        $schema = $mysql->getCurrentSchema();

        $expected = [
            'field_primary'           => [
                'name'            => 'field_primary',
                'type'            => 'int',
                'size'            => 10,
                'scale'           => 0,
                'isNullable'      => false,
                'defaultValue'    => null,
                'isAutoIncrement' => true,
                'isPrimary'       => true,
                'isUnsigned'      => false,
                'options'         => null,
            ],
            'field_blob'              => [
                'name'            => 'field_blob',
                'type'            => 'blob',
                'size'            => 65535,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_binary'            => [
                'name'            => 'field_binary',
                'type'            => 'binary',
                'size'            => 10,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_bit'               => [
                'name'            => 'field_bit',
                'type'            => 'bit',
                'size'            => 10,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_bit_default'       => [
                'name'            => 'field_bit_default',
                'type'            => 'bit',
                'size'            => 10,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => "b'1'",
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_bigint'            => [
                'name'            => 'field_bigint',
                'type'            => 'bigint',
                'size'            => 20,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => true,
                'options'         => null,
            ],
            'field_bigint_default'    => [
                'name'            => 'field_bigint_default',
                'type'            => 'bigint',
                'size'            => 19,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => 1,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => false,
                'options'         => null,
            ],
            'field_boolean'           => [
                'name'            => 'field_boolean',
                'type'            => 'tinyint',
                'size'            => 3,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => true,
                'options'         => null,
            ],
            'field_boolean_default'   => [
                'name'            => 'field_boolean_default',
                'type'            => 'tinyint',
                'size'            => 3,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => 1,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => false,
                'options'         => null,
            ],
            'field_char'              => [
                'name'            => 'field_char',
                'type'            => 'char',
                'size'            => 10,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_char_default'      => [
                'name'            => 'field_char_default',
                'type'            => 'char',
                'size'            => 10,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => 'ABC',
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_decimal'           => [
                'name'            => 'field_decimal',
                'type'            => 'decimal',
                'size'            => 10,
                'scale'           => 4,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_decimal_default'   => [
                'name'            => 'field_decimal_default',
                'type'            => 'decimal',
                'size'            => 10,
                'scale'           => 4,
                'isNullable'      => true,
                'defaultValue'    => 14.5678,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_enum'              => [
                'name'            => 'field_enum',
                'type'            => 'enum',
                'size'            => 8,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => [
                    "'xs'",
                    "'s'",
                    "'m'",
                    "'l'",
                    "'xl'",
                    "'internal'",
                ],
            ],
            'field_integer'           => [
                'name'            => 'field_integer',
                'type'            => 'int',
                'size'            => 10,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => false,
                'options'         => null,
            ],
            'field_integer_default'   => [
                'name'            => 'field_integer_default',
                'type'            => 'int',
                'size'            => 10,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => 1,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => false,
                'options'         => null,
            ],
            'field_json'              => [
                'name'            => 'field_json',
                'type'            => 'json',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_float'             => [
                'name'            => 'field_float',
                'type'            => 'float',
                'size'            => 10,
                'scale'           => 4,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_float_default'     => [
                'name'            => 'field_float_default',
                'type'            => 'float',
                'size'            => 10,
                'scale'           => 4,
                'isNullable'      => true,
                'defaultValue'    => 14.5678,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_date'              => [
                'name'            => 'field_date',
                'type'            => 'date',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_date_default'      => [
                'name'            => 'field_date_default',
                'type'            => 'date',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => '2018-10-01',
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_datetime'          => [
                'name'            => 'field_datetime',
                'type'            => 'datetime',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_datetime_default'  => [
                'name'            => 'field_datetime_default',
                'type'            => 'datetime',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => '2018-10-01 12:34:56',
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_time'              => [
                'name'            => 'field_time',
                'type'            => 'time',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_time_default'      => [
                'name'            => 'field_time_default',
                'type'            => 'time',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => '12:34:56',
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_timestamp'         => [
                'name'            => 'field_timestamp',
                'type'            => 'timestamp',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_timestamp_default' => [
                'name'            => 'field_timestamp_default',
                'type'            => 'timestamp',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => '2018-10-01 12:34:56',
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_timestamp_current' => [
                'name'            => 'field_timestamp_current',
                'type'            => 'timestamp',
                'size'            => null,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_mediumint'         => [
                'name'            => 'field_mediumint',
                'type'            => 'mediumint',
                'size'            => 7,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => true,
                'options'         => null,
            ],
            'field_mediumint_default' => [
                'name'            => 'field_mediumint_default',
                'type'            => 'mediumint',
                'size'            => 7,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => 1,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => false,
                'options'         => null,
            ],
            'field_smallint'          => [
                'name'            => 'field_smallint',
                'type'            => 'smallint',
                'size'            => 5,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => true,
                'options'         => null,
            ],
            'field_smallint_default'  => [
                'name'            => 'field_smallint_default',
                'type'            => 'smallint',
                'size'            => 5,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => 1,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => false,
                'options'         => null,
            ],
            'field_tinyint'           => [
                'name'            => 'field_tinyint',
                'type'            => 'tinyint',
                'size'            => 3,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => true,
                'options'         => null,
            ],
            'field_tinyint_default'   => [
                'name'            => 'field_tinyint_default',
                'type'            => 'tinyint',
                'size'            => 3,
                'scale'           => 0,
                'isNullable'      => true,
                'defaultValue'    => 1,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => false,
                'options'         => null,
            ],
            'field_longtext'          => [
                'name'            => 'field_longtext',
                'type'            => 'longtext',
                'size'            => 4294967295,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_mediumtext'        => [
                'name'            => 'field_mediumtext',
                'type'            => 'mediumtext',
                'size'            => 16777215,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_tinytext'          => [
                'name'            => 'field_tinytext',
                'type'            => 'tinytext',
                'size'            => 255,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_text'              => [
                'name'            => 'field_text',
                'type'            => 'text',
                'size'            => 65535,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_varbinary'         => [
                'name'            => 'field_varbinary',
                'type'            => 'varbinary',
                'size'            => 10,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_varchar'           => [
                'name'            => 'field_varchar',
                'type'            => 'varchar',
                'size'            => 10,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => null,
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
            'field_varchar_default'   => [
                'name'            => 'field_varchar_default',
                'type'            => 'varchar',
                'size'            => 10,
                'scale'           => null,
                'isNullable'      => true,
                'defaultValue'    => 'D',
                'isAutoIncrement' => false,
                'isPrimary'       => false,
                'isUnsigned'      => null,
                'options'         => null,
            ],
        ];
        $actual   = $mysql->listColumns($schema, 'co_dialect');

        $this->assertSame($expected, $actual);
    }
}
