# This file is part of Phalcon.
#
# (c) Phalcon Team <team@phalcon.io>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

name: "Phalcon CI"

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
  workflow_dispatch:

env:
  # All versions should be declared here
  PHALCON_VERSION: 6.0.0

  # For tests
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  LC_ALL: en_US.UTF-8

  # PHP extensions required by Composer
  EXTENSIONS: apcu, gettext, gd, igbinary, imagick, intl, json, mbstring, msgpack, memcached, pcov, sqlite3, yaml, redis, :memcache, openssl

permissions: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  # PHP CodeSniffer inspection
  phpcs:
    name: "Validate code style"

    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 1
          token: ${{ github.token }}

      - name: "Setup PHP"
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: '8.5'
          extensions: ${{ env.EXTENSIONS }}
          ini-values: apc.enable_cli=on, session.save_path=/tmp
          tools: pecl
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PHALCON_PATH: ext

      - name: Install development dependencies with Composer
        uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6 # v4
        with:
          composer-options: "--prefer-dist --ignore-platform-reqs"

      - name: "PHPCS"
        run: composer cs

      - name: "PHPStan"
        run: composer analyze

  unit-tests:
    name: Unit tests

    permissions:
      contents: read # to fetch code (actions/checkout)
      pull-requests: write # to comment coverage on PRs (octocov)
      actions: read # to download prior coverage artifacts (octocov)

    runs-on: ubuntu-latest

    needs:
      - phpcs

    services:
      redis:
        image: redis:8-alpine
        ports:
          - "6379:6379"
      memcached:
        image: memcached:1.6-alpine
        ports:
          - "11211:11211"
      beanstalkd:
        image: schickling/beanstalkd:latest
        ports:
          - "11300:11300"

    strategy:
      fail-fast: true
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
          token: ${{ github.token }}

      - name: "Setup platform specific environment"
        shell: pwsh
        run: |
          git config --global core.autocrlf false
          $SessionSavePath = if ("${{ runner.os }}" -eq "Windows") { 'C:\temp' } else { '/tmp' }
          Write-Output "SESSION_SAVE_PATH=$SessionSavePath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Redis Cluster
        uses: vishnudxb/redis-cluster@e29c352fa58527003afc982e96db437c0c49e6aa # 1.10.0
        with:
          master1-port: 5000
          master2-port: 5001
          master3-port: 5002
          slave1-port: 5003
          slave2-port: 5004
          slave3-port: 5005
          sleep-duration: 5 # Define the sleep duration for docker to start and ready for accepting connections (Here we set default to 5seconds)

      # Running Test
      - name: Test Redis Cluster
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-tools
          docker ps -a
          redis-cli -h 127.0.0.1 -p 5000 ping
          redis-cli -h 127.0.0.1 -p 5000 cluster nodes

      - name: "Setup PHP"
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.EXTENSIONS }}
          ini-values: apc.enable_cli=on, session.save_path=${{ env.SESSION_SAVE_PATH }}
          tools: pecl, phpize, php-config, composer:v2
          coverage: pcov
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PHALCON_PATH: ext

      - name: "Validate composer"
        run: composer validate --no-check-all --no-check-publish

      - name: "Install development dependencies with Composer"
        uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6 # v4
        with:
          composer-options: "--prefer-dist --ignore-platform-reqs"

      - name: "Setup Tests"
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            ./resources/linux-setup-locales.sh
          fi

          cp tests/support/_config/.env.default .env
          php bin/generate-db-schemas.php

      - name: "Tests with coverage"
        run: composer test-unit-coverage

      - name: Upload coverage file artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: "unit-${{ matrix.php }}.coverage"
          path: "tests/_output/coverage.cov"
          retention-days: 7

  db-mysql-tests:
    name: MySQL tests

    permissions:
      contents: read # to fetch code (actions/checkout)

    runs-on: ubuntu-latest

    needs:
      - phpcs

    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'

    services:
      mysql:
        image: mysql:8.0
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_USER: phalcon
          MYSQL_DATABASE: phalcon
          MYSQL_PASSWORD: secret
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:8-alpine
        ports:
          - "6379:6379"
      memcached:
        image: memcached:1.6-alpine
        ports:
          - "11211:11211"

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 1
          token: ${{ github.token }}

      - name: Setup platform specific environment
        shell: pwsh
        run: git config --global core.autocrlf false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.EXTENSIONS }}
          ini-values: apc.enable_cli=on, session.save_path=/tmp
          tools: pecl, phpize, php-config, composer:v2
          coverage: pcov
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PHALCON_PATH: ext

      - name: Validate composer
        run: composer validate --no-check-all --no-check-publish

      - name: Install development dependencies with Composer
        uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6 # v4
        with:
          composer-options: "--prefer-dist --ignore-platform-reqs"

      - name: Setup Tests
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            ./resources/linux-setup-locales.sh
          fi

          cp tests/support/_config/.env.default .env
          php bin/generate-db-schemas.php

      - name: Run Database Tests (MySQL)
        env:
          DATA_MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
          DATA_MYSQL_USER: root
          DATA_REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
          DATA_MEMCACHED_PORT: ${{ job.services.memcached.ports['11211'] }}
        run: composer test-db-mysql-coverage

      - name: Upload coverage file artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: "db-mysql-${{ matrix.php }}.coverage"
          path: "tests/_output/coverage.cov"
          retention-days: 7

  db-postgres-tests:
    name: PostgreSQL tests

    permissions:
      contents: read # to fetch code (actions/checkout)

    runs-on: ubuntu-latest

    needs:
      - phpcs

    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'

    services:
      postgres:
        image: postgres:18-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: phalcon
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: phalcon
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:8-alpine
        ports:
          - "6379:6379"
      memcached:
        image: memcached:1.6-alpine
        ports:
          - "11211:11211"

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 1
          token: ${{ github.token }}

      - name: Setup platform specific environment
        shell: pwsh
        run: git config --global core.autocrlf false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.EXTENSIONS }}
          ini-values: apc.enable_cli=on, session.save_path=/tmp
          tools: pecl, phpize, php-config, composer:v2
          coverage: pcov
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PHALCON_PATH: ext

      - name: Validate composer
        run: composer validate --no-check-all --no-check-publish

      - name: Install development dependencies with Composer
        uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6 # v4
        with:
          composer-options: "--prefer-dist --ignore-platform-reqs"

      - name: Setup Tests
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            ./resources/linux-setup-locales.sh
          fi

          cp tests/support/_config/.env.default .env
          php bin/generate-db-schemas.php

      - name: Run Database Tests (Postgres)
        env:
          DATA_REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
          DATA_MEMCACHED_PORT: ${{ job.services.memcached.ports['11211'] }}
        run: composer test-db-pgsql-coverage

      - name: Upload coverage file artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: "db-postgres-${{ matrix.php }}.coverage"
          path: "tests/_output/coverage.cov"
          retention-days: 7

  db-sqlite-tests:
    name: SQLite tests

    permissions:
      contents: read # to fetch code (actions/checkout)

    runs-on: ubuntu-latest

    needs:
      - phpcs

    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'

    services:
      redis:
        image: redis:8-alpine
        ports:
          - "6379:6379"
      memcached:
        image: memcached:1.6-alpine
        ports:
          - "11211:11211"

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 1
          token: ${{ github.token }}

      - name: Setup platform specific environment
        shell: pwsh
        run: git config --global core.autocrlf false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.EXTENSIONS }}
          ini-values: apc.enable_cli=on, session.save_path=/tmp
          tools: pecl, phpize, php-config, composer:v2
          coverage: pcov
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PHALCON_PATH: ext

      - name: Validate composer
        run: composer validate --no-check-all --no-check-publish

      - name: Install development dependencies with Composer
        uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6 # v4
        with:
          composer-options: "--prefer-dist --ignore-platform-reqs"

      - name: Setup Tests
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            ./resources/linux-setup-locales.sh
          fi

          cp tests/support/_config/.env.default .env
          php bin/generate-db-schemas.php

      - name: Run Database Tests (SQLite)
        env:
          DATA_REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
          DATA_MEMCACHED_PORT: ${{ job.services.memcached.ports['11211'] }}
        run: composer test-db-sqlite-coverage

      - name: Upload coverage file artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: "db-sqlite-${{ matrix.php }}.coverage"
          path: "tests/_output/coverage.cov"
          retention-days: 7

  upload-coverage:
    name: Merge coverage and report

    permissions:
      contents: read
      pull-requests: write # to comment coverage on PRs (octocov)
      actions: read # to download prior coverage artifacts (octocov)

    runs-on: ubuntu-latest

    needs:
      - phpcs
      - unit-tests
      - db-mysql-tests
      - db-postgres-tests
      - db-sqlite-tests

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
          token: ${{ github.token }}

      - name: "Setup PHP"
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: '8.3'
          extensions: ${{ env.EXTENSIONS }}
          tools: pecl, phpize, php-config, composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PHALCON_PATH: ext

      - name: "Install development dependencies with Composer"
        uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6 # v4
        with:
          composer-options: "--prefer-dist --ignore-platform-reqs"

      - name: Create directory for coverage files
        run: mkdir -p cv

      - name: Download coverage files
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          path: cv

      - name: "Merge coverage reports"
        run: mkdir -p tests/_output && php -d memory_limit=4G bin/merge-coverage.php cv tests/_output/coverage.xml

      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # v8.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sources=src
            -Dsonar.php.coverage.reportPaths=tests/_output/coverage.xml
            -Dsonar.verbose=true

      - name: "octocov"
        uses: k1LoW/octocov-action@b3b6ee60482a667950f87553abf1df63217235d9 # v1.5.1
        with:
          config: ${{ github.event_name == 'pull_request' && 'resources/octocov.pr.yml' || 'resources/octocov.yml' }}

      - name: "Upload coverage badge"
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: coverage-badge
          path: tests/_output/coverage.svg
          if-no-files-found: ignore
