name: Static Code Analysis

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  phpcs:
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    runs-on: ubuntu-20.04
    name: Tests code style validation
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Run PHP_CodeSniffer
        run: docker run --rm -v $(pwd):/data cytopia/phpcs --standard=./phpcs.xml

  stubs:
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '7.4', '8.0' ]

    name: Stubs code validation in PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: pecl
          extensions: mbstring, intl, json, imagick, redis, igbinary, apcu, msgpack, memcached, yaml, psr-1.1.0

      - name: Install System Dependencies
        run: |
          sudo apt-get update --quiet --yes 1>/dev/null
          sudo apt-get install --no-install-recommends -q -y re2c

      - name: Install Packages
        run: composer install --prefer-dist

      - name: Validate Psalm
        if: always()
        run: |
          vendor/bin/psalm src/
