name: Static Code Analysis

on:
  pull_request:
    branches:
      - master
      - v5.0.x
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  build:
    # To prevent build a particular commit use
    #     git commit -m "......... [ci skip]"
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # fetch-depth: 1
          # Full git history is needed to get a proper list of
          # changed files within `super-linter`
          fetch-depth: 0
#      - name: Run PHP_CodeSniffer
#        run: docker run --rm -v $(pwd):/data cytopia/phpcs --standard=./phpcs.xml
      # Run Linter against code base
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PHP_PHPCS: true
          VALIDATE_PHP_PHPSTAN: true
          VALIDATE_PHP_PSALM: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
